name: Maven Test CI

on:
  push:
    branches:
      - master

jobs:
  smoke-test:
    name: Smoke Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '19'
          cache: maven
    run: mvn clean test -Dbrowser=chrome -Denvironment=dev -DxmlFilePath=src\test\resources\testing-smoke.xml
