name: Maven Test CI on Windows/Chrome

on:
  push:
    branches:
      - master
      - locators

jobs:
  smoke-test:
    name: Smoke Test
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Run Smoke Test
        run: mvn clean test -Dbrowser=chrome -Denvironment=qa -DxmlFilePath="src\test\resources\testing-smoke.xml"

      - name: Upload Screenshots
        if: failure()  # Only upload artifacts if the job fails
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-screenshots
          path: target/screenshots/

      - name: Upload DOM
        if: failure()  # Only upload artifacts if the job fails
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-dom-structure
          path: target/dom/
