name: Maven Test CI on Ubuntu/Firefox

on:
  push:
    branches:
      - master
      - locators

jobs:
  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/bin/
          geckodriver --version
          firefox --version

      - name: Run Smoke Test
        run: mvn clean test -Dbrowser=chrome -Denvironment=dev -DxmlFilePath="src\test\resources\testing-smoke.xml"

      - name: Upload Screenshots
        if: failure()  # Only upload artifacts if the job fails
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-screenshots
          path: target/screenshots/

      - name: Upload DOM
        if: failure()  # Only upload artifacts if the job fails
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-dom-structure
          path: target/dom/
